-- What the visitor's screen actually showed, reported by the client.
--
-- conversation_logs answers "what did we send". It cannot answer "did they see
-- it", and those have quietly stopped being the same question:
--
--   * The worker returns one reply; the client splits it with
--     _splitIntoBubbles and paces the pieces out over several seconds. Leave
--     mid-reply and the later bubbles are never drawn. One row in
--     conversation_logs, three bubbles intended, one seen — and nothing
--     recorded the difference.
--   * OpenAIService strips **, *, and both quote characters from the reply
--     before it is displayed. The text on screen is already not the text in
--     assistant_message, so a mangling bug cannot be caught by reading the
--     server's own copy.
--   * Most of what the character "says" early on never came from the server at
--     all: the welcome script, idle nudges, the portrait, and the "having
--     trouble thinking" fallback are all written by the client. In the first
--     thirty seconds these outnumber real replies, and conversation_logs has
--     no row for any of them.
--
-- The suspicion this table exists to test is regional delivery failure — that
-- some visitors are shown far less than we think, which would explain
-- engagement that the funnel says should be higher. That diagnosis needs the
-- negative case, and the negative case is the hard part: when delivery breaks,
-- the server hears nothing, so absence of evidence is exactly what a broken
-- region looks like. So the client records intent *before* it draws, holds
-- unsent rows locally, and flushes them on the next connection that works.
-- A row with intended_at and no seen_at is the finding.
--
-- Same lesson as 0007's failure_reason column, one layer further in: there,
-- a send that never reached the worker was indistinguishable from nobody
-- typing. Here, a reply that never reached the screen is indistinguishable
-- from a reply we never made.

CREATE TABLE IF NOT EXISTS message_delivery (
    -- Generated by the client, one per bubble, before the first send attempt.
    --
    -- The primary key rather than a server id on purpose: flushes are
    -- at-least-once (a queued row is retried until it is acknowledged, and an
    -- acknowledgement can itself be lost), so the same bubble will arrive
    -- twice. Keying on the client's own id makes the retry idempotent instead
    -- of duplicating the row it was meant to complete.
    bubble_id TEXT PRIMARY KEY,

    -- Which reply this bubble is part of, and its place in it. One server
    -- reply, or one run of the welcome script, is one turn.
    --
    -- Without these, "they saw two of the four bubbles" is unanswerable: the
    -- rows are there but nothing says they belonged together or which order
    -- they were meant to arrive in. seq is 0-based and assigned at intent, so
    -- a gap in it is a bubble that was planned and never drawn.
    turn_id TEXT NOT NULL,
    seq INTEGER NOT NULL,

    -- Who and where. visit_id is the browser page load, the same id the splash
    -- beacon generates and that 0007 added to conversation_logs — so these
    -- rows join straight onto the arrive/app_ready/leave funnel and onto the
    -- messages for the same session. NULL on the mobile app, which has no page
    -- load; see docs/mobile-delivery-logging.md.
    visit_id TEXT,
    user_id TEXT NOT NULL,
    chat_id TEXT,
    character_id TEXT,

    -- The conversation_logs row this bubble came out of, when it came from the
    -- server at all. This is the join that makes the whole table useful: it
    -- turns "what we sent" and "what was shown" into one comparable pair
    -- instead of two datasets matched on a fuzzy (user, time, text) guess.
    --
    -- NULL for every client-authored origin below, and for a bubble drawn
    -- from a reply whose log id never made it back to the client.
    conversation_log_id TEXT,

    -- Where the words came from. One of:
    --   ai_reply       a real reply from the worker, split into bubbles
    --   welcome_script the scripted opening, paced by _playWelcome
    --   idle_nudge     _sendIdlePrompt, after a quiet spell
    --   portrait       _sendPortrait, the character's photo
    --   local_fallback "trouble thinking", rate-limit, translation refusal —
    --                  written by the client but shown in the character's
    --                  voice, and indistinguishable from ai_reply on screen
    --   system_banner  "Roleplay Active", isSystem: true
    --   user           the visitor's own message
    --
    -- Recorded because these fail for completely different reasons, and
    -- lumping them together would hide the one that matters. A missing
    -- ai_reply is a delivery problem; a missing welcome_script bubble is
    -- someone leaving before the opening finished, which is a pacing problem.
    origin TEXT NOT NULL,
    is_user INTEGER NOT NULL DEFAULT 0,

    -- Exactly what was put on screen, byte for byte, plus a digest of it.
    --
    -- The digest is what makes a comparison against assistant_message
    -- mechanical rather than a human squinting at two strings. Expect a
    -- systematic mismatch on ai_reply rows from the character stripping in
    -- OpenAIService — that is a known, intended difference, and the point of
    -- storing both is to tell it apart from the unintended kind.
    --
    -- text_len is kept separately so truncation can be measured even if the
    -- text itself is later trimmed for retention.
    text TEXT,
    text_sha256 TEXT,
    text_len INTEGER,

    -- The three moments, by the client's clock, ISO-8601.
    --
    --   intended_at  the client committed to showing this bubble. Written
    --                before any pacing delay, so it exists even for a bubble
    --                that is never drawn.
    --   rendered_at  it reached the widget tree.
    --   seen_at      it was actually on screen: current route, tab visible,
    --                and the bubble's box inside the scroll viewport.
    --
    -- Three columns rather than one status, because the pairs that are missing
    -- are each a different bug. intended with no rendered is delivery.
    -- rendered with no seen is a bubble drawn off-screen or into a hidden tab,
    -- which counts as delivered and unread — the distinction the engagement
    -- numbers currently cannot make.
    --
    -- All nullable, all written once. A flush that arrives late or twice
    -- COALESCEs into the row and never regresses a timestamp that is set.
    intended_at TEXT,
    rendered_at TEXT,
    seen_at TEXT,

    -- When the server wrote it, which is not when any of the above happened.
    --
    -- The client's clock is not trustworthy — it can be wrong by hours, and on
    -- a device with a bad clock every window query built on intended_at would
    -- silently exclude the session. This column is the one an admin query can
    -- rely on; the client's three are what get compared to each other.
    server_received_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- Why this bubble's turn failed, when it did: the OpenAIService
    -- lastFailureReason value ("network", "http_500", "rate_limited",
    -- "empty_response", ...). Same vocabulary as site_visits.failure_reason
    -- from 0007, deliberately, so the two can be counted together.
    failure_reason TEXT,

    -- How long the row sat in the client's queue before it landed, and how
    -- many attempts it took.
    --
    -- This is the outage measurement. A region that drops requests produces
    -- rows that arrive minutes or hours late with a high attempt count, and
    -- queued_ms is the length of the hole. Nothing server-side can see that:
    -- during the outage there is no traffic to observe.
    queued_ms INTEGER,
    flush_attempts INTEGER,

    -- Client context, for slicing failures by something actionable. Sent by
    -- the client rather than parsed from the user agent, which cannot tell you
    -- the connection was 2g or the window was 380px.
    app_version TEXT,
    locale TEXT,
    tz_offset_min INTEGER,
    connection_type TEXT,
    viewport_w INTEGER,
    viewport_h INTEGER,

    -- Filled in server-side from request.cf on the flush that carried the row.
    --
    -- The country of the *flush*, which for a queued row may not be where the
    -- bubble was shown — someone who moved or changed network reports from the
    -- new one. Good enough for finding a bad region and worth the caveat;
    -- there is no honest way to get the original location after the fact.
    country TEXT,
    colo TEXT
);

-- The finding, and the only query that has to be fast on a cold cache:
-- bubbles that were meant to be shown and have no seen_at.
CREATE INDEX IF NOT EXISTS idx_message_delivery_unseen
    ON message_delivery (seen_at, server_received_at DESC);

-- Reassembling one turn in order — "show me what this reply actually did".
CREATE INDEX IF NOT EXISTS idx_message_delivery_turn
    ON message_delivery (turn_id, seq);

-- Per-session reads, joined against the funnel rows for the same visit.
CREATE INDEX IF NOT EXISTS idx_message_delivery_visit
    ON message_delivery (visit_id, server_received_at);

-- "Is this specific region worse", sliced by origin because the answer differs
-- per origin and the aggregate hides it.
CREATE INDEX IF NOT EXISTS idx_message_delivery_country
    ON message_delivery (country, origin, server_received_at);

-- Joining a shown bubble back to the reply it was cut from.
CREATE INDEX IF NOT EXISTS idx_message_delivery_conversation_log
    ON message_delivery (conversation_log_id);
