#!/usr/bin/env node
// Generates backend/src/starters.generated.js from the app's character
// profiles, so the admin can tell a tapped starter from a typed message.
//
//   npm run gen:starters      # after editing character_profiles.dart
//
// Nothing records which message was a tap: starter_tap stores only the
// character, and input_typed is a one-shot per screen. The only way to split
// them is to compare the message text against the starters that were on offer
// — which means the worker needs the same list the app shows. Generated rather
// than hand-copied, because a stale copy would silently reclassify taps as
// typed and there would be nothing on screen to say so.
//
// The admin page's "starter (unmatched)" label is the alarm for this file
// being out of date: a session that tapped a starter but matched no known
// text says so instead of being counted wrong.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const repo = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const profiles = path.join(repo, 'lib/src/core/data/character_profiles.dart');
const chatScreen = path.join(repo, 'lib/src/features/chat/presentation/chat_screen.dart');
const out = path.join(repo, 'backend/src/starters.generated.js');

// Dart string literals: either quote style, escaped quotes, adjacent-string
// concatenation is not used inside these lists.
const strings = (s) =>
    [...s.matchAll(/(['"])((?:\\.|(?!\1).)*)\1/g)]
        .map((m) => m[2].replace(/\\'/g, "'").replace(/\\"/g, '"').replace(/\\n/g, '\n'));

const src = fs.readFileSync(profiles, 'utf8');
const asks = {};
for (const m of src.matchAll(/'([a-z_]+)':\s*CharacterProfile\(/g)) {
    const rest = src.slice(m.index);
    const block = rest.slice(0, rest.indexOf('\n  ),'));
    const list = block.match(/asks:\s*\[([\s\S]*?)\]/);
    if (list) asks[m[1]] = strings(list[1]);
}
if (!Object.keys(asks).length) {
    console.error(`No asks found in ${profiles} — refusing to write an empty list.`);
    process.exit(1);
}

// _starterPrompts appends this to every profile's asks, and falls back to a
// fixed list for characters with none. Both are read from the widget rather
// than restated here, for the same reason the asks are.
const widget = fs.readFileSync(chatScreen, 'utf8');
const getter = widget.slice(widget.indexOf('List<String> get _starterPrompts'));
const body = getter.slice(0, getter.indexOf('\n  }'));
const appended = strings(body.match(/return \[\.\.\.asks,([^\]]*)\]/)?.[1] || '');
const fallback = strings(body.match(/return const \[([\s\S]*?)\]/)?.[1] || '');

const starters = {};
for (const [id, list] of Object.entries(asks)) starters[id] = [...list, ...appended];

const banner = `// GENERATED by tool/gen_starters.mjs — do not edit.
// Regenerate with \`npm run gen:starters\` after changing the starters in
// lib/src/core/data/character_profiles.dart. See that script for why this is
// generated rather than maintained by hand.
`;

fs.writeFileSync(out, `${banner}
/// The one-tap openers each character offers, in the order shown.
export const CHARACTER_STARTERS = ${JSON.stringify(starters, null, 4)};

/// Shown for characters with no profile of their own.
export const DEFAULT_STARTERS = ${JSON.stringify(fallback, null, 4)};
`);

const n = Object.values(starters).reduce((a, l) => a + l.length, 0);
console.log(`wrote ${path.relative(repo, out)}: ${Object.keys(starters).length} characters, ${n} starters, ${fallback.length} fallback`);
